services:
  mcp-server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
